// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFh9TZ5hXn9Tsz4guUYNnL31ETYGryLc',
    appId: '1:372402795002:web:8758b29daf89d5b35d3443',
    messagingSenderId: '372402795002',
    projectId: 'the-ghost-portal',
    authDomain: 'the-ghost-portal.firebaseapp.com',
    storageBucket: 'the-ghost-portal.firebasestorage.app',
    measurementId: 'G-PJ8HG445VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTcLLqvxaftbtXOKydjUWOTRWG0_jUtc',
    appId: '1:372402795002:android:8f7b228be2608e5a5d3443',
    messagingSenderId: '372402795002',
    projectId: 'the-ghost-portal',
    storageBucket: 'the-ghost-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNKnLPUfBLQtWd5D7EXuPx8IKf42jmdFw',
    appId: '1:372402795002:ios:b923b386d91caf145d3443',
    messagingSenderId: '372402795002',
    projectId: 'the-ghost-portal',
    storageBucket: 'the-ghost-portal.firebasestorage.app',
    iosClientId: '372402795002-mqfovsfr095oi5dlae38ps07leuc6kou.apps.googleusercontent.com',
    iosBundleId: 'com.example.theGhostPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNKnLPUfBLQtWd5D7EXuPx8IKf42jmdFw',
    appId: '1:372402795002:ios:b923b386d91caf145d3443',
    messagingSenderId: '372402795002',
    projectId: 'the-ghost-portal',
    storageBucket: 'the-ghost-portal.firebasestorage.app',
    iosClientId: '372402795002-mqfovsfr095oi5dlae38ps07leuc6kou.apps.googleusercontent.com',
    iosBundleId: 'com.example.theGhostPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFh9TZ5hXn9Tsz4guUYNnL31ETYGryLc',
    appId: '1:372402795002:web:df1c3457c1a0edf25d3443',
    messagingSenderId: '372402795002',
    projectId: 'the-ghost-portal',
    authDomain: 'the-ghost-portal.firebaseapp.com',
    storageBucket: 'the-ghost-portal.firebasestorage.app',
    measurementId: 'G-1LBMGT3JCE',
  );
}
